//! The designed SFX bank (CP-6 audio identity) — committed, generated WAV assets decoded at
//! stream-open.
//!
//! The cues live as mono 16-bit 48 kHz PCM WAVs under `assets/audio/`, generated by the
//! deterministic Csound + SoX script `tools/audio/gen_sfx.py` (script-not-binary, D41/D46;
//! provenance + sha256 in `assets/audio/manifest.json`). This module `include_bytes!`s them —
//! the same discipline as `render`'s raw `.gray` font atlas — and hand-rolls the tiny RIFF
//! parse so the `pal` crate stays dependency-free (invariant #2: no platform crates here, and
//! no decoder crates either).
//!
//! A backend calls [`sample_bank`] once on stream-open (exactly where it used to call
//! [`crate::mix::synth_bank`]): each asset is decoded and linearly resampled from its authored
//! 48 kHz to the negotiated device rate, so a cue plays at the intended pitch everywhere. Both
//! backends (`pal-desktop` cpal, `pal-android` oboe/AAudio) share this one path, so the set
//! sounds identical per platform.
//!
//! **Never load-bearing, never silent:** audio must not crash a match (the backends already
//! degrade device failures to a no-op), so a cue that fails to decode falls back to its
//! [`crate::mix::synth_bank`] procedural placeholder rather than panicking or going missing.
//! With the committed assets this fallback is dead code — the tests below pin every asset as
//! decodable — but a corrupted regeneration degrades gracefully instead of muting the
//! going-dark alert channel (invariant #6).
//!
//! Floats are fine here: presentation, never the sim (invariant #1) — same scope as the rest
//! of `pal`'s render math.

use std::collections::HashMap;
use std::sync::Arc;

use crate::{MusicId, SoundId};

/// The committed cue assets, one per [`SoundId`]. The names are the contract with
/// `tools/audio/gen_sfx.py` (and its manifest) — keep both sides in sync.
pub const ASSETS: [(SoundId, &[u8]); 8] = [
    (
        SoundId::Gunfire,
        include_bytes!("../../assets/audio/gunfire.wav"),
    ),
    (
        SoundId::UnitDown,
        include_bytes!("../../assets/audio/unit_down.wav"),
    ),
    (
        SoundId::BaseHit,
        include_bytes!("../../assets/audio/base_hit.wav"),
    ),
    (
        SoundId::Capture,
        include_bytes!("../../assets/audio/capture.wav"),
    ),
    (
        SoundId::ProductionReady,
        include_bytes!("../../assets/audio/production_ready.wav"),
    ),
    (
        SoundId::HitConfirm,
        include_bytes!("../../assets/audio/hit_confirm.wav"),
    ),
    (
        SoundId::WeaponFire,
        include_bytes!("../../assets/audio/weapon_fire.wav"),
    ),
    (
        SoundId::Impact,
        include_bytes!("../../assets/audio/impact.wav"),
    ),
];

/// The committed **music** assets, one per [`MusicId`] — the going-dark score (a looping ambient
/// combat bed + the two match-end stingers), generated by `tools/audio/gen_music.py` (provenance +
/// sha256 in `assets/audio/music/manifest.json`). Same discipline as [`ASSETS`]: `include_bytes!`d
/// and hand-parsed so `pal` stays dependency-free. The names are the contract with the generator.
/// The bed is authored to loop seamlessly (whole-cycle synthesis); the resampler below preserves
/// that seam because linear interpolation of a seamless buffer is itself seamless at the wrap.
pub const MUSIC_ASSETS: [(MusicId, &[u8]); 3] = [
    (
        MusicId::CombatBed,
        include_bytes!("../../assets/audio/music/combat_bed.wav"),
    ),
    (
        MusicId::WinStinger,
        include_bytes!("../../assets/audio/music/win_stinger.wav"),
    ),
    (
        MusicId::LoseStinger,
        include_bytes!("../../assets/audio/music/lose_stinger.wav"),
    ),
];

/// Decode a mono 16-bit PCM WAV into `(sample_rate, samples)`, samples normalized to
/// `[-1.0, 1.0)`. Strict on purpose: the generator authors exactly this format, so anything
/// else (stereo, float, 8-bit, truncated) is a pipeline bug and errors rather than guessing.
/// Walks RIFF chunks (word-aligned) so an extra `LIST`/`fact` chunk from a future tool bump
/// doesn't break the parse.
pub fn decode_wav_pcm16_mono(bytes: &[u8]) -> Result<(u32, Vec<f32>), &'static str> {
    if bytes.len() < 12 || &bytes[0..4] != b"RIFF" || &bytes[8..12] != b"WAVE" {
        return Err("not a RIFF/WAVE file");
    }
    let mut pos = 12usize;
    let mut sample_rate: Option<u32> = None;
    let mut data: Option<&[u8]> = None;
    while pos + 8 <= bytes.len() {
        let id = &bytes[pos..pos + 4];
        let size = u32::from_le_bytes([
            bytes[pos + 4],
            bytes[pos + 5],
            bytes[pos + 6],
            bytes[pos + 7],
        ]) as usize;
        let body_start = pos + 8;
        let body_end = body_start.checked_add(size).ok_or("chunk size overflow")?;
        if body_end > bytes.len() {
            return Err("chunk overruns file");
        }
        let body = &bytes[body_start..body_end];
        match id {
            b"fmt " => {
                if body.len() < 16 {
                    return Err("fmt chunk too short");
                }
                let format = u16::from_le_bytes([body[0], body[1]]);
                let channels = u16::from_le_bytes([body[2], body[3]]);
                let rate = u32::from_le_bytes([body[4], body[5], body[6], body[7]]);
                let bits = u16::from_le_bytes([body[14], body[15]]);
                if format != 1 {
                    return Err("not integer PCM");
                }
                if channels != 1 {
                    return Err("not mono");
                }
                if bits != 16 {
                    return Err("not 16-bit");
                }
                if rate == 0 {
                    return Err("zero sample rate");
                }
                sample_rate = Some(rate);
            }
            b"data" => data = Some(body),
            _ => {} // skip LIST/fact/etc.
        }
        // Chunks are word-aligned: an odd-sized body is followed by one pad byte.
        pos = body_end + (size & 1);
    }
    let sr = sample_rate.ok_or("missing fmt chunk")?;
    let data = data.ok_or("missing data chunk")?;
    let samples: Vec<f32> = data
        .chunks_exact(2)
        .map(|c| i16::from_le_bytes([c[0], c[1]]) as f32 / 32768.0)
        .collect();
    if samples.is_empty() {
        return Err("empty data chunk");
    }
    Ok((sr, samples))
}

/// Linearly resample `src` from `from_hz` to `to_hz`. Linear interpolation is plenty for these
/// short one-shot cues (the authored 48 kHz is at or above every negotiated device rate we see,
/// so this is a mild down/identity conversion, not an aliasing-prone upsample of hot content).
/// Same-rate input is returned as an exact copy; degenerate input (empty, zero rate) yields an
/// empty buffer, which [`sample_bank`] treats as a decode failure.
pub fn resample_linear(src: &[f32], from_hz: u32, to_hz: u32) -> Vec<f32> {
    if src.is_empty() || from_hz == 0 || to_hz == 0 {
        return Vec::new();
    }
    if from_hz == to_hz {
        return src.to_vec();
    }
    let ratio = from_hz as f64 / to_hz as f64;
    let out_len = ((src.len() as f64 / ratio).round() as usize).max(1);
    (0..out_len)
        .map(|i| {
            let pos = i as f64 * ratio;
            let i0 = (pos as usize).min(src.len() - 1);
            let i1 = (i0 + 1).min(src.len() - 1);
            let frac = (pos - i0 as f64) as f32;
            src[i0] + (src[i1] - src[i0]) * frac
        })
        .collect()
}

/// Build the per-[`SoundId`] cue bank at device sample rate `sr` from the committed designed
/// assets — the CP-6 replacement for [`crate::mix::synth_bank`], with that synth as the
/// per-cue fallback if an asset ever fails to decode (see the module docs). Backends call this
/// once on stream-open and look voices up by id in `submit_mix` / `play_oneshot`.
pub fn sample_bank(sr: u32) -> HashMap<SoundId, Arc<Vec<f32>>> {
    // Start from the procedural placeholders so every SoundId is always present…
    let mut bank = crate::mix::synth_bank(sr);
    // …then overlay each successfully decoded designed cue.
    for (id, bytes) in ASSETS {
        if let Ok((src_hz, samples)) = decode_wav_pcm16_mono(bytes) {
            let resampled = resample_linear(&samples, src_hz, sr);
            if !resampled.is_empty() {
                bank.insert(id, Arc::new(resampled));
            }
        }
    }
    bank
}

/// Build the per-[`MusicId`] music bank at device sample rate `sr` from the committed assets — the
/// music twin of [`sample_bank`]. Each asset is decoded and resampled to `sr`; an entry that fails
/// to decode (or resamples to empty) is simply **omitted**, never faked. There is no procedural
/// fallback for music (unlike the SFX synth bank): a caller that wants the bed to never go silent
/// installs [`crate::mix::synth_music`] when [`MusicId::CombatBed`] is absent, and a missing stinger
/// just means no match-end punctuation — music is never load-bearing (invariant #6 is the *SFX*
/// alert channel, not the score), so degrading to fewer cues is fine where a missing SFX cue is not.
pub fn music_bank(sr: u32) -> HashMap<MusicId, Arc<Vec<f32>>> {
    let mut bank = HashMap::new();
    for (id, bytes) in MUSIC_ASSETS {
        if let Ok((src_hz, samples)) = decode_wav_pcm16_mono(bytes) {
            let resampled = resample_linear(&samples, src_hz, sr);
            if !resampled.is_empty() {
                bank.insert(id, Arc::new(resampled));
            }
        }
    }
    bank
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Assemble a WAV byte blob in-test: `fmt` fields + raw sample bytes, with optional junk
    /// chunks around `data` to exercise the chunk walk.
    fn wav(
        format: u16,
        channels: u16,
        rate: u32,
        bits: u16,
        data: &[u8],
        pre_junk: bool,
    ) -> Vec<u8> {
        let mut fmt = Vec::new();
        fmt.extend_from_slice(&format.to_le_bytes());
        fmt.extend_from_slice(&channels.to_le_bytes());
        fmt.extend_from_slice(&rate.to_le_bytes());
        let byte_rate = rate * channels as u32 * bits as u32 / 8;
        fmt.extend_from_slice(&byte_rate.to_le_bytes());
        let block_align = channels * bits / 8;
        fmt.extend_from_slice(&block_align.to_le_bytes());
        fmt.extend_from_slice(&bits.to_le_bytes());

        let mut body = Vec::new();
        body.extend_from_slice(b"WAVE");
        body.extend_from_slice(b"fmt ");
        body.extend_from_slice(&(fmt.len() as u32).to_le_bytes());
        body.extend_from_slice(&fmt);
        if pre_junk {
            // An odd-sized junk chunk before `data` — exercises skip + word-align padding.
            body.extend_from_slice(b"LIST");
            body.extend_from_slice(&3u32.to_le_bytes());
            body.extend_from_slice(&[0xAA, 0xBB, 0xCC, 0x00]); // 3 bytes + 1 pad
        }
        body.extend_from_slice(b"data");
        body.extend_from_slice(&(data.len() as u32).to_le_bytes());
        body.extend_from_slice(data);

        let mut out = Vec::new();
        out.extend_from_slice(b"RIFF");
        out.extend_from_slice(&(body.len() as u32).to_le_bytes());
        out.extend_from_slice(&body);
        out
    }

    fn pcm16(samples: &[i16]) -> Vec<u8> {
        samples.iter().flat_map(|s| s.to_le_bytes()).collect()
    }

    // --- decode_wav_pcm16_mono ------------------------------------------------------------

    #[test]
    fn decode_round_trips_samples_and_rate() {
        let raw = [0i16, 16384, -16384, 32767, -32768];
        let bytes = wav(1, 1, 48_000, 16, &pcm16(&raw), false);
        let (sr, samples) = decode_wav_pcm16_mono(&bytes).expect("decodes");
        assert_eq!(sr, 48_000);
        assert_eq!(samples.len(), raw.len());
        assert!((samples[0] - 0.0).abs() < 1e-6);
        assert!((samples[1] - 0.5).abs() < 1e-4);
        assert!((samples[2] + 0.5).abs() < 1e-4);
        assert!(samples[3] < 1.0 && samples[3] > 0.999);
        assert!((samples[4] + 1.0).abs() < 1e-6);
    }

    #[test]
    fn decode_skips_junk_chunks_with_odd_size_padding() {
        let bytes = wav(1, 1, 44_100, 16, &pcm16(&[100, -100]), true);
        let (sr, samples) = decode_wav_pcm16_mono(&bytes).expect("junk chunk is skipped");
        assert_eq!(sr, 44_100);
        assert_eq!(samples.len(), 2);
    }

    #[test]
    fn decode_rejects_wrong_shapes() {
        let data = pcm16(&[1, 2, 3, 4]);
        assert!(decode_wav_pcm16_mono(b"not a wav").is_err());
        assert!(decode_wav_pcm16_mono(&wav(3, 1, 48_000, 16, &data, false)).is_err()); // float
        assert!(decode_wav_pcm16_mono(&wav(1, 2, 48_000, 16, &data, false)).is_err()); // stereo
        assert!(decode_wav_pcm16_mono(&wav(1, 1, 48_000, 8, &data, false)).is_err()); // 8-bit
        assert!(decode_wav_pcm16_mono(&wav(1, 1, 0, 16, &data, false)).is_err()); // zero rate
        assert!(decode_wav_pcm16_mono(&wav(1, 1, 48_000, 16, &[], false)).is_err());
        // empty data
    }

    #[test]
    fn decode_rejects_truncated_and_overrunning_chunks() {
        let mut bytes = wav(1, 1, 48_000, 16, &pcm16(&[1, 2, 3, 4]), false);
        // Chop the tail so the declared data size overruns the file.
        bytes.truncate(bytes.len() - 3);
        assert!(decode_wav_pcm16_mono(&bytes).is_err());
        // A bare RIFF header with no chunks at all.
        assert!(decode_wav_pcm16_mono(&bytes[..12]).is_err());
    }

    // --- resample_linear ------------------------------------------------------------------

    #[test]
    fn resample_same_rate_is_identity() {
        let src = [0.0f32, 0.5, -0.5, 1.0];
        assert_eq!(resample_linear(&src, 48_000, 48_000), src.to_vec());
    }

    #[test]
    fn resample_scales_length_by_rate_ratio() {
        let src = vec![0.25f32; 480];
        let down = resample_linear(&src, 48_000, 24_000);
        let up = resample_linear(&src, 48_000, 96_000);
        assert_eq!(down.len(), 240);
        assert_eq!(up.len(), 960);
        // A constant signal stays constant through linear interpolation.
        for s in down.iter().chain(up.iter()) {
            assert!((s - 0.25).abs() < 1e-6);
        }
    }

    #[test]
    fn resample_interpolates_between_neighbours() {
        // 2x upsample of a ramp: odd output samples sit halfway between the inputs.
        let src = [0.0f32, 1.0];
        let up = resample_linear(&src, 24_000, 48_000);
        assert_eq!(up.len(), 4);
        assert!((up[0] - 0.0).abs() < 1e-6);
        assert!((up[1] - 0.5).abs() < 1e-6);
        assert!((up[2] - 1.0).abs() < 1e-6, "clamped at the last sample");
    }

    #[test]
    fn resample_degenerate_inputs_yield_empty() {
        assert!(resample_linear(&[], 48_000, 44_100).is_empty());
        assert!(resample_linear(&[1.0], 0, 44_100).is_empty());
        assert!(resample_linear(&[1.0], 48_000, 0).is_empty());
    }

    // --- the committed assets (the CP-6 contract) -------------------------------------------

    /// Every SoundId the backends can look up.
    const ALL_SOUNDS: [SoundId; 8] = [
        SoundId::Gunfire,
        SoundId::UnitDown,
        SoundId::BaseHit,
        SoundId::Capture,
        SoundId::ProductionReady,
        SoundId::HitConfirm,
        SoundId::WeaponFire,
        SoundId::Impact,
    ];

    #[test]
    fn every_committed_asset_decodes_at_48k_within_mixer_headroom() {
        // Pins the assets as valid: if a regeneration corrupts one, this fails rather than the
        // runtime silently falling back to the placeholder synth.
        for (id, bytes) in ASSETS {
            let (sr, samples) =
                decode_wav_pcm16_mono(bytes).unwrap_or_else(|e| panic!("{id:?}: {e}"));
            assert_eq!(sr, 48_000, "{id:?} authored rate");
            assert!(!samples.is_empty(), "{id:?} empty");
            // The generator normalizes to -2.9 dBFS (~0.72), inside the mixer's stacking
            // headroom — the same bound mix.rs pins for the synth placeholders.
            for &s in &samples {
                assert!((-0.8..=0.8).contains(&s), "{id:?} sample {s} too hot");
            }
        }
    }

    #[test]
    fn assets_cover_every_sound_exactly_once() {
        for &want in &ALL_SOUNDS {
            assert_eq!(
                ASSETS.iter().filter(|(id, _)| *id == want).count(),
                1,
                "{want:?} must have exactly one asset"
            );
        }
    }

    #[test]
    fn sample_bank_serves_the_designed_assets_not_the_placeholders() {
        // The bank must be the decoded assets — for every sound, the served buffer matches the
        // decoded+resampled asset (i.e. the synth fallback did NOT win).
        let bank = sample_bank(48_000);
        for (id, bytes) in ASSETS {
            let (_, samples) = decode_wav_pcm16_mono(bytes).expect("asset decodes");
            let served = bank.get(&id).expect("sound present");
            assert_eq!(
                served.as_slice(),
                samples.as_slice(),
                "{id:?} should serve the designed asset"
            );
        }
    }

    #[test]
    fn sample_bank_resamples_to_the_device_rate() {
        let at_48k = sample_bank(48_000);
        let at_24k = sample_bank(24_000);
        for &id in &ALL_SOUNDS {
            let hi = at_48k.get(&id).unwrap().len();
            let lo = at_24k.get(&id).unwrap().len();
            assert!(
                lo < hi && lo > 0,
                "{id:?}: 24 kHz bank ({lo}) should be shorter than 48 kHz ({hi})"
            );
        }
    }

    #[test]
    fn alert_palette_cues_are_pairwise_distinct() {
        // The four going-dark alert pings (engine::alert_cues reuses these SoundIds) must stay
        // separable — identical or duplicated buffers would collapse two alert kinds into one
        // sound and break the "distinct by ear" contract (invariant #6).
        let bank = sample_bank(48_000);
        let palette = [
            SoundId::Gunfire,
            SoundId::UnitDown,
            SoundId::BaseHit,
            SoundId::Capture,
        ];
        for i in 0..palette.len() {
            for j in (i + 1)..palette.len() {
                let a = bank.get(&palette[i]).unwrap();
                let b = bank.get(&palette[j]).unwrap();
                assert_ne!(
                    a.as_slice(),
                    b.as_slice(),
                    "{:?} and {:?} must sound different",
                    palette[i],
                    palette[j]
                );
            }
        }
    }

    #[test]
    fn corrupt_asset_falls_back_to_the_synth_placeholder_shape() {
        // The fallback path itself: feed the bank-building logic a bad blob and confirm the
        // synth placeholder survives (never a missing/silent cue — invariant #6).
        let mut bank = crate::mix::synth_bank(48_000);
        let placeholder = Arc::clone(bank.get(&SoundId::Gunfire).unwrap());
        // Mirror sample_bank's overlay step with a corrupt asset.
        if let Ok((src_hz, samples)) = decode_wav_pcm16_mono(b"garbage") {
            let resampled = resample_linear(&samples, src_hz, 48_000);
            if !resampled.is_empty() {
                bank.insert(SoundId::Gunfire, Arc::new(resampled));
            }
        }
        assert_eq!(
            bank.get(&SoundId::Gunfire).unwrap().as_slice(),
            placeholder.as_slice(),
            "a corrupt asset leaves the placeholder in place"
        );
    }

    // --- the committed MUSIC assets (the going-dark score) -----------------------------------

    const ALL_MUSIC: [MusicId; 3] = [
        MusicId::CombatBed,
        MusicId::WinStinger,
        MusicId::LoseStinger,
    ];

    #[test]
    fn every_music_asset_decodes_at_24k_within_headroom() {
        // Pins the music assets valid: a corrupt regeneration fails here rather than silently
        // dropping the bed / a stinger at runtime.
        for (id, bytes) in MUSIC_ASSETS {
            let (sr, samples) =
                decode_wav_pcm16_mono(bytes).unwrap_or_else(|e| panic!("{id:?}: {e}"));
            assert_eq!(sr, 24_000, "{id:?} authored rate");
            assert!(!samples.is_empty(), "{id:?} empty");
            // The bed normalizes quiet (-10 dBFS) to sit under the SFX mix; the stingers to -5 dBFS.
            // Both are inside the mixer's [-0.8, 0.8] stacking headroom.
            for &s in &samples {
                assert!((-0.8..=0.8).contains(&s), "{id:?} sample {s} too hot");
            }
        }
    }

    #[test]
    fn music_assets_cover_every_id_exactly_once() {
        for &want in &ALL_MUSIC {
            assert_eq!(
                MUSIC_ASSETS.iter().filter(|(id, _)| *id == want).count(),
                1,
                "{want:?} must have exactly one asset"
            );
        }
    }

    #[test]
    fn combat_bed_loops_seamlessly() {
        // The bed is cursor-wrapped by the mixer, so the last→first sample step must be an ordinary
        // single-sample step, not a discontinuity click (whole-cycle synthesis guarantees this).
        let (_, bed) = decode_wav_pcm16_mono(MUSIC_ASSETS[0].1).expect("bed decodes");
        assert_eq!(MUSIC_ASSETS[0].0, MusicId::CombatBed);
        let jump = (bed[0] - bed[bed.len() - 1]).abs();
        assert!(jump < 0.05, "loop wrap discontinuity {jump}");
    }

    #[test]
    fn music_bank_serves_the_assets_and_resamples_to_device_rate() {
        let at_24k = music_bank(24_000);
        let at_48k = music_bank(48_000);
        for &id in &ALL_MUSIC {
            // Present at both rates…
            let lo = at_24k.get(&id).unwrap_or_else(|| panic!("{id:?} at 24k"));
            let hi = at_48k.get(&id).unwrap_or_else(|| panic!("{id:?} at 48k"));
            // …and upsampled longer at the higher rate.
            assert!(
                hi.len() > lo.len(),
                "{id:?}: 48k ({}) > 24k ({})",
                hi.len(),
                lo.len()
            );
        }
        // At the authored rate the served bed is exactly the decoded asset (identity resample).
        let (_, bed) = decode_wav_pcm16_mono(MUSIC_ASSETS[0].1).unwrap();
        assert_eq!(
            at_24k.get(&MusicId::CombatBed).unwrap().as_slice(),
            bed.as_slice()
        );
    }

    #[test]
    fn music_ids_are_pairwise_distinct_buffers() {
        // Bed / win / lose must be three different pieces — a duplicated buffer would play the wrong
        // punctuation on a match end.
        let bank = music_bank(24_000);
        for (i, &a_id) in ALL_MUSIC.iter().enumerate() {
            for &b_id in &ALL_MUSIC[i + 1..] {
                let a = bank.get(&a_id).unwrap();
                let b = bank.get(&b_id).unwrap();
                assert_ne!(
                    a.as_slice(),
                    b.as_slice(),
                    "{a_id:?} and {b_id:?} must be different music"
                );
            }
        }
    }
}
