#!/usr/bin/env python3
"""Generate the ground **detail textures** — the seamless noise that breaks up the flat floor.

Script-not-binary (decisions.md D41/D46): this generator + the manifest entry are the committed
source of record; the raw textures are regenerable artifacts (sha256 pinned below). It bakes small,
**seamlessly tiling** grayscale detail maps with ImageMagick and emits, for each:

  * assets/textures/<name>.png    — the texture (8-bit grey; for inspection / diffing)
  * assets/textures/<name>.gray   — raw R8 bytes (SIZE*SIZE), what render/ include_bytes!s so the
                                    render crate needs NO png-decode dependency (stays wgpu +
                                    bytemuck only, the same rule as the D74 font atlas)
  * assets/textures/manifest.json — provenance (source / license / sha256 / dims / channels)

Currently one texture is baked: `ground` — a two-octave value-noise detail map sampled by the
embodied first-person floor shader (`render/src/world.wgsl`) to modulate the ground brightness so
the floor reads as grounded terrain instead of a flat slate. It tiles seamlessly so it can be
repeated across the world plane without visible seams.

## The seamless trick

ImageMagick `+noise Random` is NOT tiling on its own. The fix: blur it with `-virtual-pixel tile`,
so the blur convolution **wraps around the edges** — the blurred (and therefore the final) result
tiles with no seam. We blend a coarse octave and a finer octave (both wrap-blurred) for a bit of
structure, then `-normalize` for full contrast. `-seed` makes `+noise` reproducible, so the bytes
(and the sha256 below) are stable for a given ImageMagick build.

Render-only (invariants #1/#4): the texture is a pure presentation derivation — it never touches
the sim, carries no fog/intel (invariant #6), and can never move the per-tick checksum.

Run: `pnpm assets:textures` (or `python3 tools/textures/gen_textures.py`). Requires ImageMagick on
PATH.
"""

import hashlib
import json
import subprocess
import sys
from pathlib import Path

# ---- The contract with render::world (the GROUND_TEX_SIZE const there must match) ----------------
SIZE = 256  # square, power-of-two so GPU mips/tiling are clean
SEED = 1337  # makes +noise reproducible → stable bytes / sha256 for a given ImageMagick build
LICENSE = "CC0-1.0"  # procedurally synthesised from a seed — no third-party asset, public domain

OUT_DIR = Path(__file__).resolve().parents[2] / "assets" / "textures"


def bake_ground(png_path: Path, gray_path: Path) -> bytes:
    """Bake the seamless two-octave ground detail map → PNG (inspection) + raw R8 (engine)."""
    # Two wrap-blurred noise octaves blended, then normalised. `-virtual-pixel tile` makes every
    # blur wrap at the edges, so the result tiles seamlessly. One `magick` invocation:
    #   ( coarse octave )  ( fine octave )  -average  -normalize
    subprocess.run(
        [
            "magick",
            # coarse octave — large soft blobs (the macro tonal variation)
            "(",
            "-size", f"{SIZE}x{SIZE}", "xc:",
            "-seed", str(SEED), "+noise", "Random",
            "-colorspace", "Gray",
            "-virtual-pixel", "tile", "-blur", "0x9",
            "-auto-level",
            ")",
            # fine octave — small grain (the micro detail), a different seed so it is uncorrelated
            "(",
            "-size", f"{SIZE}x{SIZE}", "xc:",
            "-seed", str(SEED + 1), "+noise", "Random",
            "-colorspace", "Gray",
            "-virtual-pixel", "tile", "-blur", "0x2",
            "-auto-level",
            ")",
            # blend the octaves (coarse dominates), then stretch to full contrast
            "-define", "compose:args=65,35",
            "-compose", "blend", "-composite",
            "-normalize",
            "-depth", "8",
            str(png_path),
        ],
        check=True,
        capture_output=True,
    )
    # Flatten to a single-channel 8-bit grey of the exact size, then dump raw R8 bytes.
    subprocess.run(
        [
            "magick", str(png_path),
            "-colorspace", "Gray",
            "-resize", f"{SIZE}x{SIZE}!",
            "-depth", "8",
            f"gray:{gray_path}",
        ],
        check=True,
        capture_output=True,
    )
    raw = gray_path.read_bytes()
    expected = SIZE * SIZE
    if len(raw) != expected:
        raise SystemExit(f"raw ground is {len(raw)} bytes, expected {expected}")
    return raw


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    ground_png = OUT_DIR / "ground.png"
    ground_gray = OUT_DIR / "ground.gray"
    raw = bake_ground(ground_png, ground_gray)

    manifest = {
        "note": (
            "Ground detail textures, generated by tools/textures/gen_textures.py "
            "(decisions.md D41/D46). Seamlessly-tiling grayscale noise sampled by the render crate "
            "(render/src/world.wgsl) to break up the flat embodied floor. Each <name>.gray is raw "
            "R8 bytes (SIZE*SIZE) include_bytes!d straight in, so the render crate stays "
            "wgpu+bytemuck only (no png-decode dep). Render-only; regenerate with "
            "`pnpm assets:textures`."
        ),
        "source": "ImageMagick (+noise Random, wrap-blurred for seamless tiling)",
        "license": LICENSE,
        "author": "procedurally synthesised (seed-based) via ImageMagick",
        "seed": SEED,
        "textures": [
            {
                "name": "ground",
                "size": SIZE,
                "channels": 1,
                "format": "R8",
                "png_bytes": ground_png.stat().st_size,
                "png_sha256": hashlib.sha256(ground_png.read_bytes()).hexdigest(),
                "gray_bytes": len(raw),
                "gray_sha256": hashlib.sha256(raw).hexdigest(),
            }
        ],
    }
    (OUT_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"ground {SIZE}x{SIZE} R8  {len(raw)} raw bytes")
    print(f"gray sha256 {manifest['textures'][0]['gray_sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
